[app]
video_source = "local"
pexels_api_keys = []
pixabay_api_keys = []
llm_provider = "moonshot"
ollama_base_url = ""
ollama_model_name = ""
openai_api_key = ""
openai_base_url = ""
openai_model_name = "gpt-4-turbo"
moonshot_api_key = "sk-rJZd8MP8cUPAESWxbg1jHdCzjH3AnVoWkTkgEbjNPz5kQP3M"
moonshot_base_url = "https://api.moonshot.cn/v1"
moonshot_model_name = "moonshot-v1-8k"
oneapi_api_key = ""
oneapi_base_url = ""
oneapi_model_name = ""
g4f_model_name = "gpt-3.5-turbo"
azure_api_key = ""
azure_base_url = ""
azure_model_name = "gpt-35-turbo"
azure_api_version = "2024-02-15-preview"
gemini_api_key = ""
gemini_model_name = "gemini-1.0-pro"
qwen_api_key = ""
qwen_model_name = "qwen-max"
deepseek_api_key = "sk-f1ccfb22898947f695a4a7e6144b7a36"
deepseek_base_url = "https://api.deepseek.com"
deepseek_model_name = "deepseek-chat"
subtitle_provider = "edge"
endpoint = ""
material_directory = ""
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""
max_concurrent_tasks = 5
hide_config = false
wan21_api_keys = [ "ms-e8ebbe7b-f8dd-4141-99c7-70dde303e50b",]

[whisper]
model_size = "large-v3"
device = "CPU"
compute_type = "int8"

[proxy]

[azure]
speech_key = ""
speech_region = ""

[ui]
language = "zh"
hide_log = false
voice_name = "zh-CN-XiaoxiaoNeural-Female"
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "#FFFFFF"
font_size = 60

host = "192.168.1.11"
port = 3306
user = "root"
password = "90-iopjklnm,"
db_name = "media"
charset = "utf8mb4"
pool_size = 10
pool_pre_ping = true


host = "192.168.1.11"
port = 3306
user = "root"
password = "90-iopjklnm,"
db_name = "media"
charset = "utf8mb4"
pool_size = 10
pool_pre_ping = true
